// <auto-generated />
namespace flight_planner_data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AirportCode_to_airport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AirportCode_to_airport));
        
        string IMigrationMetadata.Id
        {
            get { return "202010041302395_AirportCode_to_airport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
