// <auto-generated />
namespace flight_planner_data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addedairportservice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedairportservice));
        
        string IMigrationMetadata.Id
        {
            get { return "202010051528264_Added-airport-service"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
