// <auto-generated />
namespace FlightPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class correctedflightnoid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correctedflightnoid));
        
        string IMigrationMetadata.Id
        {
            get { return "202009251628295_corrected-flightnoid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
